global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-application'
    metrics_path: "/actuator/prometheus"  # Caminho correto para o actuator/prometheus
    static_configs:
      - targets: ['192.168.100.104:8080']  # A aplicação Spring Boot rodando fora do Docker

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
